spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:53286/oauth-demo
    username: postgres
    password: majda2018
    driverClassName: org.postgresql.Driver
